name: sales
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  provider: ^6.0.5
  cloud_firestore: ^4.4.3
  awesome_dialog: ^3.0.2
  intl: ^0.17.0
  flutter_speed_dial: ^6.2.0
  pdf: ^3.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/
    - assets/image/2.0x/
    - assets/image/3.0x/

