// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXs_bWccwzd9dCxIrvlSAtSKaRYrwOV4',
    appId: '1:1045886460062:web:8665d0632248a8461a1b8f',
    messagingSenderId: '1045886460062',
    projectId: 'sales-d5bfe',
    authDomain: 'sales-d5bfe.firebaseapp.com',
    storageBucket: 'sales-d5bfe.appspot.com',
    measurementId: 'G-P0JE4RE8WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLYiLwm0tOnVLrytCCtAaXGLnl1vYd75o',
    appId: '1:1045886460062:android:1933fd2b812abc971a1b8f',
    messagingSenderId: '1045886460062',
    projectId: 'sales-d5bfe',
    storageBucket: 'sales-d5bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59t_zyQdgMmWrTPpB2jVjELiXVfO7LuY',
    appId: '1:1045886460062:ios:dffa33505c21ee771a1b8f',
    messagingSenderId: '1045886460062',
    projectId: 'sales-d5bfe',
    storageBucket: 'sales-d5bfe.appspot.com',
    iosClientId: '1045886460062-f4ffqvc1megkik71ddmenbhlc4rgp6lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sales',
  );
}
